### ISSUE TITLE
issue with queue `limit` options?

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/wascally#29] opened 2015-01-20 02:23 UTC
I'm running in to an issue where a subscriber with a `limit: ##` on a queue is stopping work after a few seconds... and i don't know why.

here's the scenario: i had some busted code in SignalLeaf, and it racked up 56,000 messages in a queue... yeah. busted code, plus a few days of time :)

so i fixed the code and put in a queue limit of 25 (instead of the unlimited, causing crashes from eating all available memory) and things worked for a few seconds, but then stopped. it would process a couple hundred messages, and then wouldn't process anymore.

the crazy part is, no messages were stuck in unacknowledged status. the code just stopped working. it would no longer pull in new messages. 

drop the limit back down to 1 and it works fine. it takes a lot longer to process them, of course, since it's limited to 1 at a time. but at least 1 doesn't stop working. 

it's not just "25" either... i tried a limit of 10, and same thing happened. processes a few batches, and then stops doing any work. i even tried a limit of 2, and it stops after a few rounds of processing.

it only seems to work with either a limit of 1, or unlimited.

any idea what this may be? have you seen wascally stop processing messages with a limit, like this?

**Comment by arobson** [comment] 2015-01-20 20:28
@derickbailey that's troubling. I'm not sure about the cause on this one. I'm wrapping up a set of refactoring/changes to another one of our libs and once that is done, I plan to tackle your PR and issues. I think I'd heard one of our services was acting odd re: no longer getting messages and I wonder if it's related to this. Thanks for the detailed bug report :+1:

**Comment by derickbailey** [comment] 2015-01-20 21:00
thanks, yo. i'm on site with a client today, but i'm going to try and dig in to this tonight or tomorrow. it affects both my personal work and my client work, so it's something i need to resolve asap. 

at the very least, i hope to be able to reproduce the problem with wascally directly. if i can, i'll post the code that i use to reproduce the problem. 

there's always the chance that it's my rabbus library, so i want to make sure it's really wascally and not my code.

**Comment by arobson** [comment] 2015-01-21 15:06
@derickbailey kind of important questions: what version of rabbitmq server are you running? Are there any other queues with unacknowledged messages at this point? There have been some RabbitMQ server/API changes since 3.3.0 that might be the underlying cause (given that you're on 3.3.0 or later and you have other queues with unacknowledged messages).

**Comment by derickbailey** [comment] 2015-01-21 15:30
RabbitMQ 3.3.5, Erlang 17

No unacknowledged messages in other queues. There were a total of around 56,000 messages between two queues. One of them had about 3,500 and the other queue had the remaining amount.

**Comment by arobson** [comment] 2015-01-21 17:40
@derickbailey - Take a look at this: https://gist.github.com/arobson/99c7d62f55463c87f77a. I am using this to run 100k messages to 2 queues. One has a limit of 10 and the other of 50. Right now, I'm 55k messages into queue 2 and 11k into queue 1 without any issues so far. The messages have hit the queues at this point so queue 1 is showing > 70k messages ready.

This is on 3.4.3 (R16B03) because this is what we're running in our prod environment. I'd be interested in seeing if this code works for you or if it blows up like you've been seeing.

Out of curiosity - what do the queue sizes in terms of memory look like?

**Comment by derickbailey** [comment] 2015-01-21 19:40
this is looking like a problem with my app-specific code, and not wascally or rabbus after all.

i just ran a test w/ 10,000+ messages in a queue using my rabbus library and it worked as expected using a limit of 50. 

sample code in question https://gist.github.com/derickbailey/7f039bbce7dad9e28bb4

(run the "receiver.js" once, to set up the queue and exchange binding, before running the sender... yeah yeah yeah, shared topology and all that :D)

**Comment by arobson** [comment] 2015-01-22 19:43
@derickbailey - one thing to check for is whether or not the consumer is going away on the queue. You can do this by pulling the queue up in the dashboard and looking at the consumer count in the overview section. If that's mysteriously dropping to 0 then we just need to figure out why.

I am working on adding debug logging to wascally so that we'll be able to turn that on when things seem odd and get a detailed view of what's happening.

**Comment by arobson** [comment] 2015-01-27 14:45
I'm going to close this issue for now, but feel free to open it back up if it turns up again and you have more information I can use to reproduce.

**Closed by arobson** 2015-01-27 14:45 UTC
Labels: bug
