### ISSUE TITLE
Promise is resolved before the message is published

### ISSUE THREAD

**Issue by krazar** [LeanKit-Labs/wascally#129] opened 2016-04-15 10:22 UTC
When publishing a message, it seems that the promise is resolved before the message is published.

To be able to reproduce this issue, you could do something like the following:

```javascript
rabbit.publish(ex, options).then( function(){    
  console.log('the message should be in queue');
  process.exit(0);
});

**Comment by arobson** [comment] 2016-05-02 15:51
@krazar - I can look into this, but keep in mind that publish confirmation happens immediately for unroutable messages. If you're getting a resolution before the management console displays the count, that could be due to any number of things. I'll check the logic to see if there's something that would trigger resolution but from what I remember when writing this, I don't resolve the promise until after the broker sends me a basic.ack (meaning, Rabbit is the one telling me when to resolve the publish promise).

**Comment by hgrubst** [comment] 2016-05-14 23:21
I'm also observing this. 
Here is the file I use to reproduce : 
```javascript
var rabbit = require('wascally')

var topology = {
    connection: {
    ...
    },
    exchanges: [
        { name: 'amq.direct', type: 'direct' },
    ],
    queues: [
        { name: 'queue-w' }
    ],
    bindings: [
        { exchange: 'amq.direct', target: 'queue-w', keys: ['test'] }
    ]
};

rabbit.configure(topology).done(function () {
    console.log('connected')
    sendMessage()
});

function sendMessage() {
    //put a breakpoint here, shut down wifi
    rabbit.publish('amq.direct', {
        routingKey: 'test',
        type: 'test',
        correlationId: 'one',
        body: { text: 'hello!' },
    }).then(function (final) {
        console.log('message acked', final)
    }, function (err) {
        console.log(err)
    })
}
```
I can shutdown the wifi on my laptop just before the publish, but can still see the `message acked` being displayed.

I tried to track it down in to amqplib. From what I could see, in channel_model.js :+1: 
```javascript
CC.publish = function(exchange, routingKey, content, options, cb) {
  this.pushConfirmCallback(cb);
  return C.publish.call(this, exchange, routingKey, content, options);
};
```
When the latter gets called, cb is null. I believe this could be the source of the issue.

Sounds pretty critical to fix as the whole message confirmation process is unreliable as it is.
Given that the channel concept is hidden, you cannot really work around it as well, by manually calling waitForConfirms for example.

**Comment by arobson** [comment] 2016-06-04 14:41
@hgrubst & @krazar - I have tracked this down and I believe it's fixed in [rabbot](https://github.com/arobson/rabbot) which is the Rabbit lib I'm transferring work to. Long story short: rabbot's API is nearly identical but doesn't attempt to provide the same failure semantics, which is important, since wascally tries to do too much.

The defect was caused because the amqplibs indicate you get a promise back from publish (like you do with sendToQueue) except you don't and the monad wrapper both wascally and rabbot use convert scalar results to a resolved promise.

Feel free to give rabbot 1.0.0-10 a try. I don't have time to back-port all the bug fixes and features in rabbot back to wascally since I'm more or less the sole maintainer at this point.

**Closed** 2016-06-04 14:41 UTC

**Comment by hgrubst** [comment] 2016-06-04 21:56
@arobson Thanks for looking into this. I'll give rabbot a look when I get time. For me this issue was too important to ignore on my project where I need strong delivery guarantees or at least know where something went wrong. In the end I went back to amqplib and rolled my own network failure management. 
I still think wascally is a great piece of work, thanks for all the effort you put into this.
