### ISSUE TITLE
node.js 4.2.2 will not exit if wascally is required

### ISSUE THREAD

**Issue by djMax** [LeanKit-Labs/wascally#112] opened 2016-01-03 05:03 UTC
Only difference between my working tape test and the one that never ends is "require('wascally')"... What socket is it opening and how can I close it?

**Comment by djMax** [comment] 2016-01-03 05:06
Looks like something to do with ackInterval?

**Comment by arobson** [comment] 2016-01-04 07:26
@djMax You can call `clearAckInterval` but why not just call process.exit when you want your service to stop? If you have particular use case, that would need something else, let me know.

**Comment by djMax** [comment] 2016-01-04 16:27
I think in general process.exit() is evil. In this particular case I have a variety of automated tests running with tape. Each test sets up and tears down the environment. If wascally doesn't provide a true shutdown method, I have to run code on the "last of all tests", which isn't great. Now I can just clearAckInterval and setAckInterval in each test, but that's a little gross because it makes me know more about wascally than a consumer should, IMHO.

**Comment by ilsken** [comment] 2016-02-04 14:55
+1 Generally I'd consider having to use process.exit to be a bug. I'd prefer if the library cleaned up cleanly, perhaps just with a `shutdown` or `close` method that takes care of this (libraries shouldn't effect the global behavior of the application)

**Comment by derickbailey** [comment] 2016-02-04 15:16
> Generally I'd consider having to use process.exit to be a bug.

i can't agree with this, as a blanket statement.

yes, there will be times when the need for process.exit is a sign of a bug... but when you have a service that needs to listen to external resources, it is expected that the service will keep the process alive and that you must call process.exit when you need to.

wascally is far from the first library to cause this in my apps. nearly every service i use, from express.js listening to http, to mongodb and oracle, will hold the app instance alive because it requires an external resource that must be properly managed.

**Comment by djMax** [comment] 2016-02-04 15:18
Not when you call the method they expose that tells them to shut down. That's all I'm asking for here. This is unquestionably a bad thing to "force." Among other things, it makes integration tests a pain in the arse (basically you have to call clearAckInterval). All I saying here is there should be an explicit shutdown mechanism that is not process.exit.

**Comment by derickbailey** [comment] 2016-02-04 15:20
> Not when you call the method they expose that tells them to shut down. That's all I'm asking for here.

that, i agree with. it was specifically the blanket statement i noted above, that i don't agree with

**Comment by djMax** [comment] 2016-02-04 15:21
Definitely fair. I was being flippant. I think a better version is "requiring someone to call process.exit() to cleanup a dependency is evil"

**Comment by ilsken** [comment] 2016-02-04 15:38
Sorry for the confusion, that is what I meant to say. If a library is forcing the application to call process.exit, I'd consider that a bug. There should be a way to say "I no longer need these resources, please cleanup anything that would keep the event loop alive". 

> wascally is far from the first library to cause this in my apps. nearly every service i use - from express.js listening to http, to mongodb and oracle - will hold the app instance alive because it requires an external resource that must be properly managed.

I understand that, however, every library I've used (including express, various database drivers etc) also provide a way to cleanly shutdown and don't require process.exit. 

Express/Node's HTTP Server are actually a perfect example of what I'm talking about. The `close` method will stop accepting new connections and run all drain current requests in the queue. Once the requests are drained, the event loop will close as expected, without calling process.exit.

Example:
````
process.once('SIGINT', function () {
    console.log('received SIGINT, gracefully draining connections..')
    server.close(function () {
        console.log('http server closed, disconnecting from message queue')
        // mq here being a wrapper I wrote for amqplib, looking to use wascally instead though :)
        mq.close().finally(console.log.bind(console, 'adios!'))
    })
})
```

**Comment by derickbailey** [comment] 2016-02-04 15:41
+1 wascally should cleanup whatever it has running when the `closeAll` method or some other method like that is called.

**Comment by ilsken** [comment] 2016-02-04 15:48
Does calling `closeAll` and  `clearAckInterval` effectively get the behavior we're looking for? 

Just wondering as I'm looking to start using wascally instead of writing my own wrapper but no way to gracefully exit is a deal breaker for me personally (mostly due to the potential for `process.exit` to hide bugs I mentioned in my previous comment).

**Comment by derickbailey** [comment] 2016-02-04 15:48
@ilsken  i did a little test based on the suggestion above, and was able to see a simple node script exit properly, with just this:

```js
var wascally = require("wascally");

wascally.clearAckInterval();
```

the process exits fine. comment out the `clearAckInterval` and it stays alive, as reported.

**Comment by djMax** [comment] 2016-02-04 15:51
Yeah, closeall/clearackinterval makes it all work.

**Comment by derickbailey** [comment] 2016-02-04 15:52
@arobson i'd suggest a couple of changes to fix this...

* move the call to `setAckInterval` out of the Broker constructor. instead, place it in the Broker's `addConnection` function
* ensure `setAckInterval` does not create a duplicate interval, if there is one already running
* have `clearAckInterval` called from the `closeAll` method

this should effectively make the `closeAll` method clean up so that a process can exit

...

while we're looking at changes, i might suggest a method name change as well:

* rename `close` to `closeConnection`
* rename `closeAll` to `close`

this would make it a bit more clear what you are closing with the `closeConnection` method, and it would add a bit more consistency with other libraries when you want to closing the entire thing down with a `close` method

**Comment by ilsken** [comment] 2016-02-04 16:00
@derickbailey Awesome, thank you for taking the time to do that! I will do some testing myself later. 

+1 for making the close method more consistent with conventions, although I do know breaking changes like that can be messy

A little more complicated but you could also make it so the interval is always cleared if there are no connections and bring it back up if a new connection is added. I haven't had a chance to look at the library internals yet so I'm not sure if that's viable.

**Comment by arobson** [comment] 2016-02-04 16:03
I'm presently in the middle of a move and kinda slammed with other OSS work. I can likely add a `shutdown` call that would clean everything up as part of the WIP I have for `wascally` now based on internal needs. Thanks for the conversation about it.

**Comment by derickbailey** [comment] 2016-02-04 16:10
as a workaround, anyone that wants to have a clean `shutdown` method for now, can do this:

```js
var wascally = require("wascally");

wascally.shutdown = function(){
  wascally.clearAckInterval();
  return wascally.closeAll();
};
```

with that in place, you can shut down wascally with one call and the node process will be allowed to exit

```js
someOtherLib.close(function(){
  wascally.shutdown();
});
```

or

```js
wascally.shutdown().then(function(){
  someOtherLib.close();
});
```

**Comment by ryanwilliamquinn** [comment] 2016-05-26 20:06
Even when I use clearkAckInterval and closeAll, sometimes the process hangs with an unacked message.  Anything I could be missing?

**Comment by arobson** [comment] 2016-06-04 18:47
@djMax - as mentioned in other threads, checkout [rabbot](https://github.com/arobson/rabbot). Wascally had a lot of issues with this sort of thing due to how aggressively it would re-establish channels and connections.

If you're not very careful to have handlers set up for every message type your service can receive, this exact scenario will happen. You might try putting a custom unhandled message strategy in place and console.log that it's happening so you can identify the cause and resolve it.

**Closed by arobson** 2016-06-04 18:47 UTC
Labels: enhancement
