### ISSUE TITLE
Handler to Queue binding

### ISSUE THREAD

**Issue by joshrivers** [LeanKit-Labs/wascally#87] opened 2015-08-10 18:47 UTC
I was writing up a test app, and ran into a behavior I wasn't expecting and I'm curious if there is a way to resolve it.

I made two wascally connections to my rabbit server, each in their own closure, following the topology pattern from the pubsub pattern. Each handler was subscribed to an independent queue, but handled the same message type. The queues were bound to a single exchange in fanout mode.

It looks like what happened is this: both handlers got two copies of each message, one from each queue. If one handler ack'd messages and the other one nack'd them, both queues would be drained. I believe this is because the messages are routed in memory from the individual queues through a shared set of Postal topics.

Is there a way to strictly bind a handler to only receive messages from it's queues, or does the in-memory Postal routing lose that information?

**Comment by arobson** [comment] 2015-08-10 20:15
@joshrivers - ultimately the first thing to consider is that wascally was designed for communication between separate processes and will not behave as you'd like if you connect it multiple times. In general, I would say it is an anti-pattern to have multiple connections to Rabbit as AMQP is built to multiplex on a single connection. (The one exception I can think of being connecting to multiple vhosts). 

The issue you are seeing is not because postal loses routing info but because the handlers are registered against the same message type so that each handler receives a copy of each message. Beyond that I'm not entirely sure what would happen with differing scenarios. 

If all you need is messaging between components within the same process, all you need is postal. If you want inter-process communication then wascally is a good fit but you shouldn't run into scenarios where you'd be consuming messages published from the same process.

**Comment by joshrivers** [comment] 2015-08-10 21:44
I agree with your point about multiple connections to the server from the same process. It was just the first thing I tried to contain the scopes of my subscriptions. The two connections are not the producer and the consumer, but rather two separate consumers.

So, is there a way to have two consumers in the same process reading from separate queues, but receiving the same type of message and to keep things separated? If not, that's cool...I'm not sure I have an actual use case, I'm just trying to feel around and find the limitations or learn that I'm doing it wrong :)

**Comment by derickbailey** [comment] 2015-08-10 22:31
that can certainly be done by using unique message types between your queues. For example, if you have Q1 and Q2, messages of type "foo.bar" should only go to Q1 while messages of type "baz.quux" should only go to Q2.

In your consumer code, you would use the same connection but have multiple handle statements:

```js
wascally.handle("foo.bar", (msg) => {
  // ...
});

wascally.handle("baz.quux", (msg) => {
  // ...
});
```

Your exchange and queue binding should be set up to ensure that only messages of a specific type go to a specific queue, in this case.

**Comment by joshrivers** [comment] 2015-08-10 22:35
This requires the sender to send a separate message for each destination, though, correct? I can't have a single sender and use fanout, and my senders must ultimately know about the destinations rather than having the Rabbit exchanges making those determinations?

**Comment by derickbailey** [comment] 2015-08-10 23:21
> This requires the sender to send a separate message for each destination, though, correct? 

Your sender knows the message type. You can use the message type as the routing key, and route the messages to the appropriate queue with your exchanges.

>  I can't have a single sender and use fanout, and my senders must ultimately know about the destinations rather than having the Rabbit exchanges making those determinations?

I'm not sure I understand the questions, here... can you explain a little more about what you're trying to accomplish?

I'm probably missing something in what you're trying to do. I keep thinking you shouldn't be using a fanout, but it looks like you're trying to use a fanout. 

going back to your original question:

> Is there a way to strictly bind a handler to only receive messages from it's queues

Yes. Use routing keys to ensure the message goes to a queue that has consumers that can handle that type of message. Use the routing key as the message type, and you'll be good to go. This is basically what I do in my apps. 

but again, I think i'm misunderstanding something in what you're trying to do and I've probably got some wrong assumptions in my head because of that.

**Comment by derickbailey** [comment] 2015-08-10 23:27
still trying to understand things based on what you've already said... i'm probably missing something obvious, here.. sorry.

> Each handler was subscribed to an independent queue, but handled the same message type. 

are you looking to have multiple handlers for the same message type, in order to process more messages, faster? or ... what's the goal of having one worker consume messages of the same type, from different queues?

**Comment by joshrivers** [comment] 2015-08-11 19:34
You're probably right that I don't have a sensible use case. Currently I'm working on a piece of oversimplified sample code just to exercise the library. I ran into an edge case and wanted to understand it.

It looks like in a given worker process using wascally, you don't want to have more than one handler with a given message type unless you want all handlers to receive all messages of that type, regardless of their queue in Rabbit. 

For most of the production code examples I can think of, I think this is fine. I had just ported a simplistic sample app from ampqlib to wascally and it behaved differently, and I wanted to know if I was missing something. I was expecting handlers to be bound to queue+messagetype not simply messagetype.

I have real use cases where I want fanout and have multiple handlers of the same message types from different queues, but those uses would involve the handlers running in different processes, not sharing a process.

So, I think I understand now, and ultimately it was the in-memory semantics of using Postal that confused me a little bit.

**Comment by derickbailey** [comment] 2015-08-11 20:11
> It looks like in a given worker process using wascally, you don't want to have more than one handler with a given message type unless you want all handlers to receive all messages of that type, regardless of their queue in Rabbit.

yup. that part of wascally confused me at first, as well. i think there are some potential advantages to doing this, but it is something that has to be accounted for when you design the app.

**Comment by arobson** [comment] 2015-08-11 20:19
@joshrivers - the design decision to have handlers decoupled from queues is one that comes from having worked with messaging libs where every handler had to specify a type and channel. This made the code pretty sensitive to topology changes and any use of auto-generated queue names got more complicated. 

It wouldn't be impossible to make it so that a handler would only consider messages from a particular queue but given the additional complexity it would add to the consumer code, I'd like to know of a really solid use case that warranted it before building it in :)

**Comment by joshrivers** [comment] 2015-08-11 20:21
@arobson Those are important considerations I hadn't thought of. I think it's good the way it is, and hopefully this thread will help make it clear if anyone comes searching later.

**Comment by jwalton** [comment] 2015-08-18 16:44
Here's two use cases I'm running into right now, where I want to know what queue a message came from:

* I'm working on an existing project, and I want to move away from using `ampqlib` and start using wascally, but in my existing project I use the message type "create" to mean different things on different exchanges.  You can make the argument that I should use unique types project wide, and we can debate that, but sadly this is not the reality I live in right now.  :)

* I have publisher that publishes some event occurred, let's say "user.created".  This goes to a topic exchange - different parts of the system might be interested only in user messages, others might only be interested in *.created.  These messages go to multiple queues which have different behavior; for example, I have one named queue that acts like a work queue, and one or more "notification" processes listen on that queue to send an email to each new user as they are created.  These need to ack or nack depending on how sending the email goes.  I have a bunch of web server processes, and they all listen on anonymous queues; when a user gets created or modified they need to invalidate their caches.  These guys always ack the message back.  When I'm running the system locally in debug mode, all these different processes are all running in one node.js process, though, because it makes life a lot easier, and there's no really good reason to launch a fleet of micro services locally (in fact, in production, some of them run together in a single process, too.)  So, when I get a "user.created" message through "handle", how do I know which queue it came from?  How do I know whether this is the named queue, and I should be sending an email and nacking if it fails, vs. one of the anonymous queues, where I should be clearing a cache and then always acking?

**Comment by dermidgen** [comment] 2015-09-30 23:29
I have a similar issue to @joshrivers and @jwalton though I'm not migrating libraries.

My topology consists of several fanout and topic exchanges with a queue for each micro-service that will be listening.

In order to make life a bit easier we had attempted to use Rabbus on top of Wascally, but it was abstracting us a bit too far away from Rabbit.  Instead we have created very simple Publisher and Consumer libraries so the rest of our stack can quickly publish or subscribe to their respective exchanges and queues.

Each time a Consumer is instantiated, it sets up a handler for the given message type, passes topology/connection info via `rabbit.configure(topology)`, then sets up the subscription on the given queue.

When instantiating multiple Consumers to handle different message types on the same queue, there seem to be issues with Consumers only handling and acking even messages; odd messages seem to have issues.  When firing the consumers back up, the odd messages are still there.  However this time, even though the handler sees them, as it tries to ack them nothing seems to happen. I can see in DEBUG the ack batch build, but it never fires. I was only able to get them to clear by switching all queues to `noBatch`.

What I don't know is whether calling `rabbit.configure()` for each instantiation is causing some issues with the connections/channels and multiplexing in some way.

**Comment by derickbailey** [comment] 2015-10-01 02:51
@dermidgen 

> What I don't know is whether calling rabbit.configure() for each instantiation is causing some issues with the connections/channels and multiplexing in some way.

I can't speak to the rest of the issue... but yes, this will cause issues. there was another discussion (offline) where a wascally user saw channel leaks in excess of 25,000 channels due to re-initializing wascally before sending every message.

you won't have quite that bad of a problem - but it will still cause problems.

also - sorry about rabbus. i made a lot of mistakes when i built that. i really need to clean it up. doesn't even do everything I need it to do, right now... but, time is a premium :)

**Comment by dermidgen** [comment] 2015-10-01 13:07
@derickbailey thanks for the quick response. I suspected something was up there.

**Comment by dermidgen** [comment] 2015-10-01 15:05
I may be speaking too soon, but preliminary testing indicates that _all_ of my anomalies were resolved by ensuring a single call to `rabbit.configure()` per process.

I think this statement may close this thread: It is critical that all handlers within a process are bound to a single rabbit connection; a single rabbit.configure call.

@jwalton I believe I can answer your question by saying that you can wrap things in your own classes that track the message type and queue and directly call `rabbit.startSubscription()`.  If doing things this way, make sure you do _not_ use the `subscribe: true` property when defining queues in your topology.

@derickbailey thanks for your input and hard work on wascally. May I kindly suggest an update to the documentation that somewhere elaborates on maintaining a single connection per process and mentions that you probably only want to be calling `rabbit.configure()` once per process.

**Comment by derickbailey** [comment] 2015-10-01 15:31
@dermidgen all that thanks for hardwork belongs to @arobson! i'm just trying to be a contributing part of the community. :)

and yes, i agree - would be good to update the docs to mention only calling configure once

**Comment by arobson** [comment] 2016-01-04 08:02
Due to the number of issues that have come up for _lots_ of folks around multiple calls to configure, one of the changes we made recently was to make all calls for creation of queues, exchanges, bindings and subscriptions idempotent. Ideally, you should only call configure once, but calling it multiple times no longer causes all the problems it did.

@dermidgen - to answer your other questions:

### Is there way to force flush the ack/nack/reject queue?
Not really and you shouldn't be manipulating this directly if you want batching behavior. Rabbit is _very_ fragile when it comes to batching. If you want low-level control of this, turn off batching behavior at the queue level and process it manually.

### Is there a way to know when ack/nack/reject has completed?
If you call close on the connection, it returns a promise that should only resolve after all pending batch operations on all queues have completed (if possible). There is an event that's fired every time a batch queue is emptied but it's not currently exposed outside the lib. Before trying to work out how to make that available, can you help me understand why that's something you need to have in your application code?

###Is it okay to use the consumerTag as a way of sorting handlers/queues?
The consumer tag is only intended to allow you to identify your consumer with Rabbit when doing things like cancelling a subscription.  I wouldn't use it outside of that.

It sounds like a lot of folks want the ability to handle a message type uniquely based on the queue it is arriving on. I may need to explore ways to support this (even though it's a pattern I avoid in topology design for lots of reasons).

**Closed by arobson** 2016-01-04 08:02 UTC
Labels: documentation / demo, help wanted
